site_name: VCFormer
repo_url: https://github.com/abdenlab/VCFormer
site_description: Read and flatten VCF data into DataFrames

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
